name: ui_for_diana_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  intl: ^0.15.7
  share: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ali_landscape.png
    - images/logo.png
    - images/butternut_squash_soup.png
    - images/cherry_pie.png
    - images/chopped_beet_leaves.png
    - images/pesto_pasta.png
    - images/roasted_chicken.png
    - images/spanakopita.png
    - images/spinach_onion_salad.png
#    - images/icons/fish.png
#    - images/icons/healthy.png
#    - images/icons/main.png
    - images/meat.png
    - images/quick.png
    - images/spicy.png
    - images/veggie.png
#    - images/logo_small.png
    - images/india_chennai_flower_market.png
    - images/india_thanjavur_market.png
    - images/india_tanjore_bronze_works.png
    - images/india_tanjore_market_merchant.png
    - images/india_tanjore_thanjavur_temple.png
    - images/india_pondicherry_salt_farm.png
    - images/india_chennai_highway.png
    - images/india_chettinad_silk_maker.png
    - images/india_tanjore_thanjavur_temple_carvings.png
    - images/india_chettinad_produce.png
    - images/india_tanjore_market_technology.png
    - images/india_pondicherry_beach.png
    - images/india_pondicherry_fisherman.png
#    - imagess/backpack.png
#    - images/products/belt.png
    - images/cup.png
    - images/deskset.png
    - images/dress.png
    - images/earrings.png
    - images/flatwear.png
    - images/hat.png
    - images/jacket.png
    - images/jumper.png
    - images/kitchen_quattro.png
    - images/napkins.png
    - images/planters.png
    - images/platter.png
    - images/scarf.png
    - images/shirt.png
    - images/sunnies.png
    - images/sweater.png
    - images/sweats.png
    - images/table.png
    - images/teaset.png
    - images/top.png
    - images/ali.png
    - images/peter.png
    - images/sandra.png
    - images/stella.png
    - images/trevor.png
#    - images/bg_hero.png
#    - images/bg_runner.png
#    - images/fg_hero.png
#    - images/ic_circle_arrow.png
#    - images/run_path.png
#    - images/welcome_hello.png
#    - images/welcome_explore_flutter.png
#    - images/welcome_flutter_logo.png
#    - images/welcome_documentation.png
#    - images/welcome_documentation_focus.png
#    - images/ic_documentation.png
#    - images/welcome_playground.png
#    - images/welcome_pop_1.png
#    - images/welcome_pop_2.png
#    - images/welcome_pop_3.png
#    - images/welcome_pop_4.png

#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
